[package]
name = "stator_ffi"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
stator_core.workspace = true
log.workspace = true

[lints]
workspace = true
