[workspace]
members = [
    "crates/stator_core",
    "crates/stator_ffi",
    "crates/stator_test262",
    "crates/st8",
]
resolver = "2"

[workspace.dependencies]
bumpalo = "3.20.2"
log = "0.4.29"
env_logger = "0.11.9"
bitflags = "2.11.0"
smallvec = "1.15.1"
parking_lot = "0.12.5"
thiserror = "2.0.18"
criterion = { version = "0.8.2", features = ["html_reports"] }
