[workspace]
members = [
    "crates/stator_core",
    "crates/stator_ffi",
    "crates/stator_test262",
    "crates/st8",
]
resolver = "2"

[workspace.lints.rust]
unsafe_op_in_unsafe_fn = "deny"
missing_docs = "warn"

[workspace.dependencies]
stator_core = { path = "crates/stator_core" }
