[package]
name = "st8"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "st8"
path = "src/main.rs"

[dependencies]
stator_core.workspace = true
stator_core = { path = "../stator_core" }
env_logger.workspace = true
log.workspace = true

[lints]
workspace = true
